#!/bin/bash
##### Loop through a Flux directory and attempt to run all executable scripts  #####
#####            /etc/flux/system/epilog     for    /etc/flux/system/epilog.d  #####

SCRIPT=""

for SCRIPT in /etc/flux/system/epilog.d; do 
	echo "Running: "$SCRIPT
	/etc/flux/system/epilog.d/$SCRIPT
done
